name: Hawser Agent
slug: hawser
version: "1.1.7"
description: Hawser agent for Dockhand (Edge mode)

arch:
  - amd64
  - aarch64

startup: services
boot: auto

privileged:
  - SYS_ADMIN

map:
  - docker_socket

host_network: false


options:
  dockhand_server_url: ""
  token: ""

schema:
  dockhand_server_url: str
  token: password
